### ISSUE TITLE
Parser の呼び出し方法はどうするか

### ISSUE THREAD

**Issue by pine** [mfnewwind/Dr-Naming#11]
## 例
- CLI
- require

``` js
var Parser = require('...');

var options = { ... };
var parser = new Parser(options);

parser.parse('filename.ext', function (err, results) {
    if (err) { console.error(err); }
    console.log('Parser results = ', results);
});
```

**Comment by pine** [comment]
議論用

**Comment by pine** [comment]
## 案

### レイヤ

パースするファイルの TaskQueue <-> 抽象化 Parser <-> ファイル種類ごとのパーサー

### ファイル種類別パーサー

ファイル種類ごとのパーサーは、インターフェイスは Node で、パース処理の実装は問わない。非同期

**Comment by nekobato** [comment]
Parseを実行するプロセスは分けるか、もしくは独立して動くモジュールとして分離したい。

QueueはDBに蓄積し、ParserがDBへQueueを逐次取りに行くのが安定していると思う。

**Comment by nekobato** [comment]
Parserは独立したプロセス（or Cron）にした方がいいのかな？

**Comment by pine** [comment]
Parser 呼び出し側が別プロセスなら、Parser は別プロセスじゃなくてもいいんじゃない?

**Comment by nekobato** [comment]
あ、APIと繋がってる関数とは別プロセスという意味で。

 TaskWorker（溜まっているQueueを取りに行く） <-> 抽象化 Parser <-> Parser　でひとまとまりです。

**Comment by pine** [comment]
別プロセスでもいいんじゃない? 別プロセスじゃなくてもいいと思うけど。

**Comment by pine** [comment]
呼び出し形式 (外部パーサー) を追加
https://github.com/mfnewwind/newwind/wiki/%E8%A8%80%E8%AA%9E%E3%83%91%E3%83%BC%E3%82%B5%E3%83%BC%E4%BB%95%E6%A7%98

**Comment by pine** [comment]
TaskWarker は、サーバーと同じプロセス内でインターバル回せばいいっすかね?

**Comment by pine** [comment]
同一プロセスでタイマーで回します! Closed
