### ISSUE TITLE
Parser で抽出する項目について決める

### ISSUE THREAD

**Issue by pine** [mfnewwind/Dr-Naming#12]
#### CSS
- クラス名
- ID 名
- name 属性
- etc ...
#### Java
- クラス名
- インターフェイス名
- メンバ名
- 変数名
- パッケージ名

**Comment by pine** [comment]
言語に共通する仕様
- attr (種別)
- name (名前)
- line (行数)
- count (個数)

**Comment by pine** [comment]
変数って、定義のみ抽出するのか? 使っている場所は全部取るのか?

**Comment by pine** [comment]
## CLI で パーサーを呼び出す場合の出力例

``` java
class Test {
  public static void main(String[] args) {
    for (int i = 0; i < 10; ++i) {
      System.out.println(i);
    }
  }
}
```

CSV?

``` csv
class,Test,1,1
variable,args,2,1
variable,i,3,3
variable,i,4,1
```

JSON?

``` json
[
  ["class","Test",1,1],
  ["variable","args",2,1],
  ["variable","i",3,3],
  ["variable","i",4,1]
]
```

**Comment by nekobato** [comment]
後でコードハイライトで見るUIが欲しいから、カウントとは別に場所は全て抽出しておきたいな

**Comment by kazuman519** [comment]
コメントもほしいところ

**Comment by pine** [comment]
これまでのまとめ
- 識別子種類 (例: 変数名, 関数名, モジュール名, etc ...)
- 識別子名 (例: foo, Bar, getBaz, etc ...)
- コメント (例: ユーザー数, ユーザーの状態を返す関数, etc ...)
- 場所 (識別子がある行数)

**Comment by pine** [comment]
成果は Wiki に移動
https://github.com/mfnewwind/newwind/wiki/%E8%A8%80%E8%AA%9E%E3%83%91%E3%83%BC%E3%82%B5%E3%83%BC%E4%BB%95%E6%A7%98
