### ISSUE TITLE
フロントで使うJSライブラリを決定する

### ISSUE THREAD

**Issue by nekobato** [mfnewwind/Dr-Naming#15]
他の人の要望が無いなら一存で決めちゃいますよ

**Comment by pine** [comment]
lodash

**Comment by pine** [comment]
browserify

**Comment by nekobato** [comment]
AJAX：superagent

**Comment by pine** [comment]
なにそれ、いいなｗｗｗ 使いやすそう

**Comment by nekobato** [comment]
最近のJSフレームワークはhttp request周りをサポートしないので、軽量ajaxライブラリはほとんどsuperagent使ってる

**Comment by pine** [comment]
てっきり jQuery 併用かと

**Comment by nekobato** [comment]
jQueryのAjaxは実装がレガシーだし、ajaxのためだけに巨大な他の部分が付いてくるのは宜しくないと思ってる

**Comment by pine** [comment]
browserifty V.S. webpack

**Comment by nekobato** [comment]
webpack使ってみたいと思ってるけど複数ポイント出力に用がないならbrowserifyでいいと思ってる

**Comment by pine** [comment]
browserify でいいんじゃね

**Comment by nekobato** [comment]
hi

**Comment by nekobato** [comment]
最後、JSフレームワーク
Reactjs vs Vuejs

**Comment by pine** [comment]
Vue は結構触ったことあるけど、React もやってみたい感
フロントやりたい人いたら希望言ったらいいと思う

**Comment by kazuman519** [comment]
開発のしやすさではどちらなのだろうか

**Comment by nekobato** [comment]
正直ReactはVirtual DOMとflux flowについて勉強する必要があるので来週までに作れって言われて使う選択肢ではないと思う
Vuejsもじゃんって言われたら仕方ないけど、JQueryよりはマシ

**Comment by pine** [comment]
Vue はわりあい学習コスト少ないのでは

**Comment by nekobato** [comment]
異論なければVuejsでいきましょう！

**Comment by pine** [comment]
GO しましょう

**Comment by kazuman519** [comment]
ウェイ

**Comment by nekobato** [comment]
![](http://gyazo.com/3e6390fb0dcc6ab2fb8a84c3995d82ad.png)

#26

**Comment by pine** [comment]
Issue は決定するところまでなんで、クローズします

**Comment by pine** [comment]
なんかあったら再オープンして
