### ISSUE TITLE
[ユーザーページ] レポジトリ一覧に表示する情報を決める

### ISSUE THREAD

**Issue by kazuman519** [mfnewwind/Dr-Naming#22]

**Comment by pine** [comment]
所有者、レポジトリ名、GitHub へのリンク

**Comment by kazuman519** [comment]
更新日時もほしい

**Comment by pine** [comment]
確かにあったらいいね

**Comment by ghost** [comment]
レポジトリ名クリック　→　解析ページでおｋ？

**Comment by kazuman519** [comment]
企画書の方を見る限りは、既にサービスにインポートしているレポジトリリストっぽいから、
レポジトリ名クリック　→　解析結果ページがいいね（解析結果リスト or コードページ？）
