### ISSUE TITLE
gulpfileにlessの設定を追加

### ISSUE THREAD

**Issue by nekobato** [mfnewwind/Dr-Naming#24]
エントリポインヨは`src/stylesheets`
エンドポインヨは`public/stylesheets`　になります
長いって言うな！
長いね！

**Comment by nekobato** [comment]
cssは一つのファイルにまとめる？
それともファイルごとに出力する？

**Comment by pine** [comment]
gulpfile めんどいんで、一つ派

**Comment by nekobato** [comment]
じゃあ全てのプロジェクトstylesheetは`public/stylesheets/style.css`に集約しよう

**Comment by pine** [comment]
OK

**Comment by nekobato** [comment]
完☆了
