### ISSUE TITLE
フロントエンドライブラリ設置

### ISSUE THREAD

**Issue by nekobato** [mfnewwind/Dr-Naming#26]
フォルダ配置 or cdnからの読み込みまで
- lodash
- superagent
- vuejs
#25 #15

**Comment by nekobato** [comment]
bowerで入れます

**Comment by nekobato** [comment]
やっぱやめとこう。素で入れます

**Comment by pine** [comment]
どっちでもいいんじゃね

**Comment by nekobato** [comment]
npm install で入れました
bowerなんていらんかったんや！

**Comment by pine** [comment]
だいたい npm にあるよね
