### ISSUE TITLE
[Parser] PerlのParserを作成する

### ISSUE THREAD

**Issue by nekobato** [mfnewwind/Dr-Naming#3]
要らないなら消してください

**Comment by pine** [comment]
PPI - search.cpan.org
http://search.cpan.org/~mithaldu/PPI-1.220/lib/PPI.pm

**Comment by pine** [comment]
技術的雑談-PPIを使ってみる
http://www.himajin2001.com/fswiki/wiki.cgi?page=%B5%BB%BD%D1%C5%AA%BB%A8%C3%CC-PPI%A4%F2%BB%C8%A4%C3%A4%C6%A4%DF%A4%EB

**Comment by pine** [comment]
PPI って何なんだろう
http://kiririmode.hatenablog.jp/entry/20081019/p1

**Comment by hiyoko9191** [comment]
変数定義：
http://search.cpan.org/dist/PPI/lib/PPI/Statement/Variable.pm
メソッド定義：
http://search.cpan.org/~mithaldu/PPI/lib/PPI/Statement/Sub.pm

**Comment by pine** [comment]
https://github.com/mfnewwind/perl-parser

**Comment by pine** [comment]
Close
問題があったら別 Issue
