### ISSUE TITLE
[Parser] JavaのParserを作成する

### ISSUE THREAD

**Issue by nekobato** [mfnewwind/Dr-Naming#4]
要らないなら消してください

**Comment by kazuman519** [comment]
現在調査中

**Comment by kazuman519** [comment]
kono [4:59 PM] 
javadoc集計するやつならあったきがしつつ

maruyama [4:59 PM] 
まじめにやるなら構文解析するのがいいとおもう

maruyama [5:00 PM]
java の bnfをくわせて、compiler compiler (yacc / javacc)とかにくわせて解析するか

maruyama [5:00 PM]
もしくは

AST 作る系のライブラリがあるはず、jacocoとかカバレッジ作る系のライブラリの中身見てみるといいとおもう

maruyama [5:01 PM]
あるいは

maruyama [5:01 PM]
groovyのAST解析がよいらしいから、groovyの構文解析器にくわせるのも手かも

maruyama [5:02 PM](java 文法 < groovyの文法 なので)

**Comment by pine** [comment]
流石 Java 豊富

**Comment by kazuman519** [comment]
コメントとメソッド名のオブジェクトがバラバラで取られるからマッチングめんどい

**Comment by kazuman519** [comment]
インナークラスがあった場合めんどい（とりあえず考えないでいいか）

**Comment by pine** [comment]
一旦 Close 問題があったら別 Issue
