### ISSUE TITLE
[Parser] JavaScriptのParserを調査する

### ISSUE THREAD

**Issue by nekobato** [mfnewwind/Dr-Naming#5]
要らないなら消してください

**Comment by pine** [comment]
GitHub
marijnh/acorn
acorn - A small, fast, JavaScript-based JavaScript parser
https://github.com/marijnh/acorn

**Comment by pine** [comment]
https://github.com/mfnewwind/acorn-test

**Comment by pine** [comment]
調査が済んで作成に入るのでクローズ
